---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.000'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MyQueryShow
name: MyQueryShow
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Amon2: 0
  DateTime: 0
  DateTime::Format::HTTP: 0
  DateTime::Format::MySQL: 0
  HTML::FillInForm::Lite: 0
  Plack::Middleware::ReverseProxy: 0
  Text::Xslate: 0
  Text::Xslate::Bridge::TT2Like: 0
  Time::Piece: 0
version: 0.01
